input {
  beats {
    port => 5044
  }
}

filter {
    if [service] == "rest" {
        json {
            source => "message"
            target => "message"
        }

        if [message.returning] {
            json_encode {
                source => "returning"
                target => "returning"
            }

            if [message.returning] !~ /^\{.*\}$/ and [message.returning] !~ /^\[.*\{.*\}.*\]$/ {
                mutate {
                    update   => { "message.returning"=> '{"value":%{message.returning}}'}
                }
            }

            json {
                source => "message.returning"
                target => "message.returning"
            }
        }

        if [message.parameters] {
            json_encode {
                source => "message.parameters"
                target => "message.parameters"
            }

            if [message.parameters] !~ /^\{.*\}$/ and [message.parameters] !~ /^\[.*\{.*\}.*\]$/  {
                mutate {
                    update   => { "message.parameters"=> '{"value":%{message.parameters}}'}
                }
            }

            json {
               source => "message.parameters"
               target => "message.parameters"
            }
        }
    }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "log-%{[service]}-%{+YYYY.MM.dd}"
  }
}