listen_addresses = '*'

logging_collector = on
log_directory = '/var/lib/postgresql/logs'
log_filename = 'postgresql.log'
log_statement = 'none'
log_min_error_statement = error
log_min_messages = warning
log_rotation_age = 1d
log_rotation_size = 10MB


