spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/archive
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

file:
  upload-path:
    base: "C:\\Users\\kerich\\Desktop\\Java\\myProjects\\uploadedFileArchive"
    poster: "${file.upload-path.base}\\poster"