volumes:
 mssql_data:

services:
 mssql:
  image: mcr.microsoft.com/mssql/server:2025-latest
  container_name: mssql
  ports:
    - "1433:1433"
  environment:
   MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}
   ACCEPT_EULA: "Y"
  volumes:
    - mssql_data:/var/opt/mssql
  restart: on-failure