input {
    elastic_agent {
      port => 5044
      ssl_enabled => true
      ssl_certificate_authorities => ["${ELASTIC_STACK_LOGSTASH_CA_CRT_FILE}"]
      ssl_certificate => ["${ELASTIC_STACK_LOGSTASH_SERVER_CRT_FILE}"]
      ssl_key => ["${ELASTIC_STACK_LOGSTASH_SERVER_KEY_FILE}"]
      ssl_client_authentication => "required"
    }
}

filter {
    if [container][name] == "logstash" {
        if [message] =~ /^\[/ {
            grok {
              match => { "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\]\[%{LOGLEVEL:log.level}%{SPACE}\]\[%{DATA:logger}%{SPACE}\](\[%{DATA:thread}\])?(\[%{DATA:hash}\])?%{GREEDYDATA:message}" }
              overwrite => [ "message" ]
              target => "logstash"
            }
        }
    }

    else if [container][name] == "elasticsearch" {
        if [message] =~ /^\{\"/ {
            json {
                source => "message"
                target => "elasticsearch"
            }
        }
    }

    else if [container][name] == "kibana" {
        if [message] =~ /^\[/ {
            grok {
              match => { "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\]\[%{LOGLEVEL:log.level}%{SPACE}\]\[%{DATA:service}\]%{SPACE}(\[%{DATA:component}\])?%{GREEDYDATA:message}" }
              overwrite => [ "message" ]
              target => "kibana"
            }
        }
    }

    else if [container][name] == "fleet-server" {
        if [message] =~ /^\{\"/ {
            json {
                source => "message"
                target => "fleet-server"
            }
        }
    }

    else if [container][name] == "elastic-agent" {
        if [message] =~ /^\{\"/ {
            json {
                source => "message"
                target => "elastic-agent"
            }
        }
    }

    else if [container][name] == "postgres" {
        grok {
            match => { "message" => [
                  "%{TIMESTAMP_ISO8601:timestamp} %{WORD:timezone} \[%{NUMBER:pid}\] %{WORD:log.level}: %{GREEDYDATA:message}",
                  "%{GREEDYDATA:message}"
            ]}
            overwrite => [ "message" ]
            target => "postgres"
        }
    }

    else if [container][name] == "rest" {
        json {
            source => "message"
            target => "rest"
        }

        if [message.returning] {
            json_encode {
                source => "returning"
                target => "returning"
            }

            if [message.returning] !~ /^\{.*\}$/ and [message.returning] !~ /^\[.*\{.*\}.*\]$/ {
                mutate {
                    update   => { "message.returning"=> '{"value":%{message.returning}}'}
                }
            }

            json {
                source => "message.returning"
                target => "message.returning"
            }
        }

        if [message.parameters] {
            json_encode {
                source => "message.parameters"
                target => "message.parameters"
            }

            if [message.parameters] !~ /^\{.*\}$/ and [message.parameters] !~ /^\[.*\{.*\}.*\]$/  {
                mutate {
                    update   => { "message.parameters"=> '{"value":%{message.parameters}}'}
                }
            }

            json {
               source => "message.parameters"
               target => "message.parameters"
            }
        }
    }
}

output {
     elasticsearch {
       hosts => ["https://elasticsearch:9200"]
       data_stream => true
       api_key => ["${ELASTIC_STACK_LOGSTASH_CONF_OUTPUT_ELASTICSEARCH_API_KEY}"]
       ssl_enabled => true
       ssl_certificate_authorities => ["${ELASTIC_STACK_LOGSTASH_CA_CRT_FILE}"]
    }
}