services:
  postgres:
    image: postgres:12.22-bookworm
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: archive
    volumes:
      - ../../DB/postgres_data:/var/lib/postgresql/data
      - ./configuration/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./logs/DB:/var/lib/postgresql/logs
    command: ["postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]
    profiles:
      - dev

  filebeat:
    image: elastic/filebeat:8.16.2
    container_name: filebeat
    ports:
      - "9000:9000"
    volumes:
      - ./configuration/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#      - ./logs:/var/lib/docker/containers:ro
      - ./logs/rest:/usr/share/filebeat/logs/rest:ro
      - ./logs/DB:/usr/share/filebeat/logs/DB:ro
      - ./logs/logstash:/usr/share/filebeat/logs/logstash:ro
    entrypoint: ["filebeat", "-e"]
    depends_on:
      - logstash
    profiles:
      - dev

  logstash:
    build:
      context: ./dockerFile/logstash
      dockerfile: DockerFile
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./configuration/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    profiles:
      - dev

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    profiles:
      - dev

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    profiles:
      - dev